// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// LogSumExp
double LogSumExp(arma::colvec logX);
RcppExport SEXP _brand_LogSumExp(SEXP logXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type logX(logXSEXP);
    rcpp_result_gen = Rcpp::wrap(LogSumExp(logX));
    return rcpp_result_gen;
END_RCPP
}
// trial
arma::colvec trial(arma::colvec X, arma::colvec M, arma::colvec S);
RcppExport SEXP _brand_trial(SEXP XSEXP, SEXP MSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(trial(X, M, S));
    return rcpp_result_gen;
END_RCPP
}
// UPD_Sticks_Beta_cpp
arma::colvec UPD_Sticks_Beta_cpp(arma::mat AB, int L, double alphaDP);
RcppExport SEXP _brand_UPD_Sticks_Beta_cpp(SEXP ABSEXP, SEXP LSEXP, SEXP alphaDPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type AB(ABSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< double >::type alphaDP(alphaDPSEXP);
    rcpp_result_gen = Rcpp::wrap(UPD_Sticks_Beta_cpp(AB, L, alphaDP));
    return rcpp_result_gen;
END_RCPP
}
// StickBreaker_cpp
arma::colvec StickBreaker_cpp(arma::colvec V);
RcppExport SEXP _brand_StickBreaker_cpp(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(StickBreaker_cpp(V));
    return rcpp_result_gen;
END_RCPP
}
// Upd_alphabeta_t_cpp
arma::mat Upd_alphabeta_t_cpp(arma::mat Y, arma::mat effe_train, arma::mat effe_test, arma::mat sigma_train, arma::mat sigma_test, arma::colvec pidir, arma::colvec omega, int J, int n, int L, int t, arma::colvec poss_lab);
RcppExport SEXP _brand_Upd_alphabeta_t_cpp(SEXP YSEXP, SEXP effe_trainSEXP, SEXP effe_testSEXP, SEXP sigma_trainSEXP, SEXP sigma_testSEXP, SEXP pidirSEXP, SEXP omegaSEXP, SEXP JSEXP, SEXP nSEXP, SEXP LSEXP, SEXP tSEXP, SEXP poss_labSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type effe_train(effe_trainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type effe_test(effe_testSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_train(sigma_trainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_test(sigma_testSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type pidir(pidirSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type poss_lab(poss_labSEXP);
    rcpp_result_gen = Rcpp::wrap(Upd_alphabeta_t_cpp(Y, effe_train, effe_test, sigma_train, sigma_test, pidir, omega, J, n, L, t, poss_lab));
    return rcpp_result_gen;
END_RCPP
}
// DN
arma::colvec DN(arma::colvec X, arma::colvec M, arma::colvec S);
RcppExport SEXP _brand_DN(SEXP XSEXP, SEXP MSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(DN(X, M, S));
    return rcpp_result_gen;
END_RCPP
}
// Upd_alphabeta_t_cpp_SLICE
arma::mat Upd_alphabeta_t_cpp_SLICE(arma::mat Y, arma::mat effe_train, arma::mat effe_test, arma::mat sigma_train, arma::mat sigma_test, arma::colvec pidir, arma::colvec omega, arma::colvec Ui, arma::colvec xi, int J, int n, int L, arma::colvec poss_lab);
RcppExport SEXP _brand_Upd_alphabeta_t_cpp_SLICE(SEXP YSEXP, SEXP effe_trainSEXP, SEXP effe_testSEXP, SEXP sigma_trainSEXP, SEXP sigma_testSEXP, SEXP pidirSEXP, SEXP omegaSEXP, SEXP UiSEXP, SEXP xiSEXP, SEXP JSEXP, SEXP nSEXP, SEXP LSEXP, SEXP poss_labSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type effe_train(effe_trainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type effe_test(effe_testSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_train(sigma_trainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_test(sigma_testSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type pidir(pidirSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Ui(UiSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type poss_lab(poss_labSEXP);
    rcpp_result_gen = Rcpp::wrap(Upd_alphabeta_t_cpp_SLICE(Y, effe_train, effe_test, sigma_train, sigma_test, pidir, omega, Ui, xi, J, n, L, poss_lab));
    return rcpp_result_gen;
END_RCPP
}
// Update_effe_test_t_cpp
arma::mat Update_effe_test_t_cpp(arma::mat Y, arma::mat alphabeta, int L, int t, arma::colvec tau_k, arma::colvec R, arma::mat sigma_test, arma::colvec ak);
RcppExport SEXP _brand_Update_effe_test_t_cpp(SEXP YSEXP, SEXP alphabetaSEXP, SEXP LSEXP, SEXP tSEXP, SEXP tau_kSEXP, SEXP RSEXP, SEXP sigma_testSEXP, SEXP akSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alphabeta(alphabetaSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type tau_k(tau_kSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_test(sigma_testSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ak(akSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_effe_test_t_cpp(Y, alphabeta, L, t, tau_k, R, sigma_test, ak));
    return rcpp_result_gen;
END_RCPP
}
// Update_effe_train_t_cpp
arma::mat Update_effe_train_t_cpp(arma::mat Y, arma::mat alphabeta, int G, int t, arma::mat f_bar_g, arma::mat sigma_train, double KAPPAG);
RcppExport SEXP _brand_Update_effe_train_t_cpp(SEXP YSEXP, SEXP alphabetaSEXP, SEXP GSEXP, SEXP tSEXP, SEXP f_bar_gSEXP, SEXP sigma_trainSEXP, SEXP KAPPAGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alphabeta(alphabetaSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type f_bar_g(f_bar_gSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_train(sigma_trainSEXP);
    Rcpp::traits::input_parameter< double >::type KAPPAG(KAPPAGSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_effe_train_t_cpp(Y, alphabeta, G, t, f_bar_g, sigma_train, KAPPAG));
    return rcpp_result_gen;
END_RCPP
}
// Update_sigma_test_t_cpp
arma::mat Update_sigma_test_t_cpp(arma::mat Y, arma::mat alphabeta, arma::mat effe_test, int L, int t, double asig, double bsig);
RcppExport SEXP _brand_Update_sigma_test_t_cpp(SEXP YSEXP, SEXP alphabetaSEXP, SEXP effe_testSEXP, SEXP LSEXP, SEXP tSEXP, SEXP asigSEXP, SEXP bsigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alphabeta(alphabetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type effe_test(effe_testSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type asig(asigSEXP);
    Rcpp::traits::input_parameter< double >::type bsig(bsigSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_sigma_test_t_cpp(Y, alphabeta, effe_test, L, t, asig, bsig));
    return rcpp_result_gen;
END_RCPP
}
// Update_sigma_train_t_cpp
arma::mat Update_sigma_train_t_cpp(arma::mat Y, arma::mat alphabeta, arma::mat effe_train, int G, int t, arma::mat a_priorG, arma::mat b_priorG);
RcppExport SEXP _brand_Update_sigma_train_t_cpp(SEXP YSEXP, SEXP alphabetaSEXP, SEXP effe_trainSEXP, SEXP GSEXP, SEXP tSEXP, SEXP a_priorGSEXP, SEXP b_priorGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alphabeta(alphabetaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type effe_train(effe_trainSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type a_priorG(a_priorGSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type b_priorG(b_priorGSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_sigma_train_t_cpp(Y, alphabeta, effe_train, G, t, a_priorG, b_priorG));
    return rcpp_result_gen;
END_RCPP
}
// Update_tau_l
arma::colvec Update_tau_l(double a_tau, double b_tau, arma::mat effe_test, int L, int t, arma::colvec OOR, arma::colvec a_l);
RcppExport SEXP _brand_Update_tau_l(SEXP a_tauSEXP, SEXP b_tauSEXP, SEXP effe_testSEXP, SEXP LSEXP, SEXP tSEXP, SEXP OORSEXP, SEXP a_lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type b_tau(b_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type effe_test(effe_testSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type OOR(OORSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type a_l(a_lSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_tau_l(a_tau, b_tau, effe_test, L, t, OOR, a_l));
    return rcpp_result_gen;
END_RCPP
}
// Update_a_l
arma::colvec Update_a_l(arma::mat effe_test, int L, arma::colvec tau_l, arma::colvec R, double s, int t, arma::colvec OneOverR);
RcppExport SEXP _brand_Update_a_l(SEXP effe_testSEXP, SEXP LSEXP, SEXP tau_lSEXP, SEXP RSEXP, SEXP sSEXP, SEXP tSEXP, SEXP OneOverRSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type effe_test(effe_testSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type tau_l(tau_lSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type R(RSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type OneOverR(OneOverRSEXP);
    rcpp_result_gen = Rcpp::wrap(Update_a_l(effe_test, L, tau_l, R, s, t, OneOverR));
    return rcpp_result_gen;
END_RCPP
}
// Upd_ZETA_t_SLICE
arma::mat Upd_ZETA_t_SLICE(arma::mat Y, arma::mat effe_ALL, arma::mat sigma_ALL, arma::colvec log_omegatilde, arma::colvec Uitilde, arma::colvec xitilde, int J, int n, int L, arma::colvec poss_lab);
RcppExport SEXP _brand_Upd_ZETA_t_SLICE(SEXP YSEXP, SEXP effe_ALLSEXP, SEXP sigma_ALLSEXP, SEXP log_omegatildeSEXP, SEXP UitildeSEXP, SEXP xitildeSEXP, SEXP JSEXP, SEXP nSEXP, SEXP LSEXP, SEXP poss_labSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type effe_ALL(effe_ALLSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma_ALL(sigma_ALLSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type log_omegatilde(log_omegatildeSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type Uitilde(UitildeSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type xitilde(xitildeSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type poss_lab(poss_labSEXP);
    rcpp_result_gen = Rcpp::wrap(Upd_ZETA_t_SLICE(Y, effe_ALL, sigma_ALL, log_omegatilde, Uitilde, xitilde, J, n, L, poss_lab));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_brand_LogSumExp", (DL_FUNC) &_brand_LogSumExp, 1},
    {"_brand_trial", (DL_FUNC) &_brand_trial, 3},
    {"_brand_UPD_Sticks_Beta_cpp", (DL_FUNC) &_brand_UPD_Sticks_Beta_cpp, 3},
    {"_brand_StickBreaker_cpp", (DL_FUNC) &_brand_StickBreaker_cpp, 1},
    {"_brand_Upd_alphabeta_t_cpp", (DL_FUNC) &_brand_Upd_alphabeta_t_cpp, 12},
    {"_brand_DN", (DL_FUNC) &_brand_DN, 3},
    {"_brand_Upd_alphabeta_t_cpp_SLICE", (DL_FUNC) &_brand_Upd_alphabeta_t_cpp_SLICE, 13},
    {"_brand_Update_effe_test_t_cpp", (DL_FUNC) &_brand_Update_effe_test_t_cpp, 8},
    {"_brand_Update_effe_train_t_cpp", (DL_FUNC) &_brand_Update_effe_train_t_cpp, 7},
    {"_brand_Update_sigma_test_t_cpp", (DL_FUNC) &_brand_Update_sigma_test_t_cpp, 7},
    {"_brand_Update_sigma_train_t_cpp", (DL_FUNC) &_brand_Update_sigma_train_t_cpp, 7},
    {"_brand_Update_tau_l", (DL_FUNC) &_brand_Update_tau_l, 7},
    {"_brand_Update_a_l", (DL_FUNC) &_brand_Update_a_l, 7},
    {"_brand_Upd_ZETA_t_SLICE", (DL_FUNC) &_brand_Upd_ZETA_t_SLICE, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_brand(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
