# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LogSumExp <- function(logX) {
    .Call(`_brand_LogSumExp`, logX)
}

trial <- function(X, M, S) {
    .Call(`_brand_trial`, X, M, S)
}

UPD_Sticks_Beta_cpp <- function(AB, L, alphaDP) {
    .Call(`_brand_UPD_Sticks_Beta_cpp`, AB, L, alphaDP)
}

StickBreaker_cpp <- function(V) {
    .Call(`_brand_StickBreaker_cpp`, V)
}

Upd_alphabeta_t_cpp <- function(Y, effe_train, effe_test, sigma_train, sigma_test, pidir, omega, J, n, L, t, poss_lab) {
    .Call(`_brand_Upd_alphabeta_t_cpp`, Y, effe_train, effe_test, sigma_train, sigma_test, pidir, omega, J, n, L, t, poss_lab)
}

DN <- function(X, M, S) {
    .Call(`_brand_DN`, X, M, S)
}

Upd_alphabeta_t_cpp_SLICE <- function(Y, effe_train, effe_test, sigma_train, sigma_test, pidir, omega, Ui, xi, J, n, L, poss_lab) {
    .Call(`_brand_Upd_alphabeta_t_cpp_SLICE`, Y, effe_train, effe_test, sigma_train, sigma_test, pidir, omega, Ui, xi, J, n, L, poss_lab)
}

Update_effe_test_t_cpp <- function(Y, alphabeta, L, t, tau_k, R, sigma_test, ak) {
    .Call(`_brand_Update_effe_test_t_cpp`, Y, alphabeta, L, t, tau_k, R, sigma_test, ak)
}

Update_effe_train_t_cpp <- function(Y, alphabeta, G, t, f_bar_g, sigma_train, KAPPAG) {
    .Call(`_brand_Update_effe_train_t_cpp`, Y, alphabeta, G, t, f_bar_g, sigma_train, KAPPAG)
}

Update_sigma_test_t_cpp <- function(Y, alphabeta, effe_test, L, t, asig, bsig) {
    .Call(`_brand_Update_sigma_test_t_cpp`, Y, alphabeta, effe_test, L, t, asig, bsig)
}

Update_sigma_train_t_cpp <- function(Y, alphabeta, effe_train, G, t, a_priorG, b_priorG) {
    .Call(`_brand_Update_sigma_train_t_cpp`, Y, alphabeta, effe_train, G, t, a_priorG, b_priorG)
}

Update_tau_l <- function(a_tau, b_tau, effe_test, L, t, OOR, a_l) {
    .Call(`_brand_Update_tau_l`, a_tau, b_tau, effe_test, L, t, OOR, a_l)
}

Update_a_l <- function(effe_test, L, tau_l, R, s, t, OneOverR) {
    .Call(`_brand_Update_a_l`, effe_test, L, tau_l, R, s, t, OneOverR)
}

Upd_ZETA_t_SLICE <- function(Y, effe_ALL, sigma_ALL, log_omegatilde, Uitilde, xitilde, J, n, L, poss_lab) {
    .Call(`_brand_Upd_ZETA_t_SLICE`, Y, effe_ALL, sigma_ALL, log_omegatilde, Uitilde, xitilde, J, n, L, poss_lab)
}

